# Generated by Django 5.0.2 on 2024-04-23 13:05

import DEMOAPP.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
        migrations.AddField(
            model_name='video',
            name='classname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='subjname',
            field=models.CharField(choices=[('english', 'ENGLISH'), ('maths', 'MATHS'), ('malayalam', 'MALAYALAM'), ('dance', 'DANCE'), ('art', 'Art & Craft')], default='english', max_length=50),
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(null=True, upload_to='video/%y', validators=[DEMOAPP.validators.file_size]),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
