from django.urls import path
from . import views

urlpatterns = [
    path('', views.hi,name="home"),
    path('home', views.home, name="homepage"),
    path('thome', views.thome, name="thome"),
    path('ahome', views.ahome, name="ahome"),
    path('phome', views.phome, name="phome"),
    path('parent',views.parent,name="parent"),
    path('about', views.about, name="about"),
    path('contact', views.contact, name="contact"),
    path('teacher',views.teacher,name="teacher"),
    path('game1',views.game1,name="game1"),
    path('game2',views.game2,name="game2"),
    path('game3',views.game3,name="game3"),
    path('teachersignup',views.teachersignup,name="teachersignup"),
    path('parentsignup',views.parentsignup,name="parentsignup"),
    path('aloginf',views.aloginf,name="aloginf"),
    path('ploginf',views.ploginf,name="ploginf"),
    path('tloginf',views.tloginf,name="tloginf"),
    path('alogin',views.alogin,name="alogin"),
    path('adminhome',views.adminhome,name="adminhome"),
    path('plogin',views.plogin,name="plogin"),
    path('tlogin',views.tlogin,name="tlogin"),
    path('alogout',views.alogout,name="alogout"),
    path('plogout',views.plogout,name="plogout"),
    path('tlogout',views.tlogout,name="tlogout"),

    path('teachers', views.teachers, name="teachers"),
    path('teacher_list',views.teacher_list,name="teacher_list"),
    path('teacher_approve',views.teacher_approve,name="teacher_approve"),
    path('teacher_list1',views.teacher_list1,name="teacher_list1"),
    path('parent_list',views.parent_list,name="parent_list"),

path('aparent_list',views.aparent_list,name="aparent_list"),
path('aview_vacc_list',views.aview_vacc_list,name="aview_vacc_list"),
path('aview_feedback',views.aview_feedback,name="aview_feedback"),
path('adel_teacher',views.adel_teacher,name="adel_teacher"),
path('adel_parent',views.adel_parent,name="adel_parent"),
path('adel_vacc',views.adel_vacc,name="adel_vacc"),
    path('add_vacc',views.add_vacc,name="add_vacc"),
    path('addvacc',views.addvacc,name="addvacc"),
    path('vacc_list',views.vacc_list,name="vacc_list"),

path('pview_teachers',views.pview_teachers,name="pview_teachers"),
path('pview_vaccination',views.pview_vacc_list,name="pview_vaccination"),
path('psent_feedback',views.psent_feedback,name="psent_feedback"),
path('psent_feedback1',views.psent_feedback1,name="psent_feedback1"),
path('pview_feedback',views.pview_feedback,name="pview_feedback"),
path('pdel_feedback',views.pdel_feedback,name="pdel_feedback"),
path('pedit_profile',views.pedit_profile,name="pedit_profile"),
path('pedit_profile1',views.pedit_profile1,name="pedit_profile1"),
path('tedit_profile',views.tedit_profile,name="tedit_profile"),
path('tedit_profile1',views.tedit_profile1,name="tedit_profile1"),

path('tview_feedback',views.tview_feedback,name="tview_feedback"),

path('tadd_video',views.tadd_video,name="tadd_video"),
path('tview_video',views.tview_video,name="tview_video"),
path('tdel_video',views.tdel_video,name="tdel_video"),
path('pview_video',views.pview_video,name="pview_video"),
path('aview_video',views.aview_video,name="aview_video"),
path('usent_feedback',views.usent_feedback,name="usent_feedback"),
]
